Feat/faceit oauth
lucasmonstro/faceit-blacklist pull request #4
Opened 2021-01-30 03:17 UTC by luqezman

## Status
**READY**

## Migrations
NO

## Description
Add faceit auth module

## Type of change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Steps to Test or Reproduce
Go to `http://localhost:3000/faceit/callback` to be redirect to faceit prompt login

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-01-30 13:59 UTC, luqezman commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +export class FetchOrCreateBlacklist {
Change name to `FetchOrCreateBlacklistService`

2021-01-30 14:09 UTC, luqezman commented on apps/api/src/app/auth/jwt.strategy.ts
> +import { FaceitIDToken } from '@faceit-blacklist/interfaces';
sort imports

2021-01-30 14:44 UTC, luqezman commented on apps/api/src/app/auth/faceit.strategy.ts
> +        _profile /* TODO: add type */,
fix this

2021-01-30 14:44 UTC, luqezman commented on apps/api/src/app/auth/faceit.strategy.ts
> +        done /* TODO: add type */
fix this

2021-01-30 14:49 UTC, luqezman commented
Add unit tests for each component

2021-01-30 15:38 UTC, luqezman commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +export class FetchOrCreateBlacklist {
done.

2021-01-30 15:38 UTC, luqezman commented on apps/api/src/app/auth/jwt.strategy.ts
> +import { FaceitIDToken } from '@faceit-blacklist/interfaces';
done.

2021-02-21 06:07 UTC, felinto-dev requested changes

2021-02-21 06:07 UTC, felinto-dev commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.spec.ts
> +          useValue: { create: jest.fn(), findOne: jest.fn() },
What do you think about creating a separate file to mock the "Blacklist" schema?
You can reuse the same mock between different spec tests. If you think it is not necessary is ok too.

2021-02-21 06:16 UTC, lucasmonstro commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +export class FetchOrCreateBlacklistService {
when you apply this approach, you avoid a "god class" and follow SRP.

2021-02-21 06:16 UTC, lucasmonstro commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +    const blacklist = await this.blacklistModel.findOne({ faceitId });
This is the current model, not a boolean.

2021-02-21 06:17 UTC, lucasmonstro commented on docker-compose.yml
>  version: '3.7'
I think this is not important here.

2021-02-21 06:18 UTC, lucasmonstro commented on libs/interfaces/src/lib/faceit.ts
> +  birthdate: string;
This is a type returned by faceit oauth.

2021-02-21 06:19 UTC, lucasmonstro commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.spec.ts
> +          useValue: { create: jest.fn(), findOne: jest.fn() },
For now, is not needed.

2021-02-21 06:19 UTC, lucasmonstro commented on docker-compose.yml
>      image: bitnami/mongodb:4.2
Is it really necessary?

2021-02-21 06:21 UTC, lucasmonstro commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +  async fetchOrCreate(faceitId: string): Promise<BlacklistDocument> {
This is my service, the entry point, here you can have some type of complexity. In this case, Im just calling a function to get Blacklist by faceit id, this is the same calling a normal function from 3rd package.

2021-02-21 07:11 UTC, felinto-dev commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +    const blacklist = await this.blacklistModel.findOne({ faceitId });
Excellent

2021-02-21 07:21 UTC, felinto-dev commented on apps/api/src/app/auth/fetch-or-create-blacklist.service.ts
> +  async fetchOrCreate(faceitId: string): Promise<BlacklistDocument> {
I don't know how but you need to rename this function. There is no need to say "fetch" because you are using Typescript's "types" feature **which ensures that you will always return an object** and never **undefined**.

2021-02-21 07:25 UTC, felinto-dev commented on docker-compose.yml
>      image: bitnami/mongodb:4.2
Absolutely. The alternative would be that if a bug occurred in a new version of MongoDB made available on DockerHub and in parallel in your application, you would not be able to know where the source of the problem is and would waste hours on it, including a lot of frustration.

If you think that it does not happen in real life, check this video:
https://www.youtube.com/watch?v=xgcIJggKtmY

2021-02-21 07:28 UTC, felinto-dev commented on docker-compose.yml
>  version: '3.7'
It's just good practice to use docker.
https://docs.docker.com/compose/compose-file/compose-versioning/

If you use docker-compose v3+, probably I will understand that you would use docker swarm or other advanced featured. So, change the version is optional.

2021-02-22 08:08 UTC, lucasmonstro commented
Add api e2e tests

2021-02-24 07:49 UTC, felinto-dev approved these changes

2021-02-24 08:08 UTC, merged