Feat/add player to blacklist
lucasmonstro/faceit-blacklist pull request #5
Opened 2021-02-24 15:52 UTC by lucasmonstro

2021-02-24 15:52 UTC, lucasmonstro commented on apps/api/src/app/auth/guards/gql-auth.guard.ts
> +  getRequest(context: ExecutionContext) {
add return type or todo

2021-02-25 06:15 UTC, felinto-dev requested changes

2021-02-25 12:03 UTC, lucasmonstro commented on apps/api/src/app/blacklist/resolvers/add-player-to-blacklist/add-player-to-blacklist.resolver.ts
> +    return await this.addPlayerToBlacklistService.add(ownerFaceitId, input);
done

2021-02-25 12:09 UTC, lucasmonstro commented on apps/api/src/app/blacklist/resolvers/add-player-to-blacklist/add-player-to-blacklist.resolver.spec.ts
> +      faceitId: faker.random.uuid(),
done

2021-02-25 12:22 UTC, lucasmonstro commented on apps/api/src/app/blacklist/services/add-player-to-blacklist/add-player-to-blacklist.service.ts
> +    return true;
done

2021-02-25 15:39 UTC, felinto-dev requested changes

2021-02-26 00:39 UTC, felinto-dev approved these changes

2021-02-26 00:39 UTC, merged